# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-07 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('min_cost', models.PositiveIntegerField(verbose_name='Min. cost')),
                ('max_cost', models.PositiveIntegerField(verbose_name='Max. cost')),
                ('min_duration', models.DurationField(verbose_name='Min. duration')),
                ('max_duration', models.DurationField(verbose_name='Max. duration')),
            ],
        ),
        migrations.CreateModel(
            name='Stand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name')),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station.Box')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name')),
            ],
        ),
        migrations.AddField(
            model_name='box',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station.Station'),
        ),
    ]
