# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-07 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0003_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
        migrations.AddField(
            model_name='job',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Completed'),
        ),
    ]
