# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 06:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0005_auto_20160108_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.TextField(max_length=128, verbose_name='Manufacturer')),
                ('model', models.TextField(max_length=128, verbose_name='Model')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='car',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='station.Car'),
        ),
    ]
